name: 'rideshare_dbt'
version: '1.0.0'
config-version: 2

profile: 'rideshare_dbt'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  rideshare_dbt:
    +file_format: delta
    staging:
      +materialized: view
      +schema: gold
    marts:
      +materialized: table
      +schema: gold

snapshots:
  rideshare_dbt:
    +target_schema: gold
    +file_format: delta

vars:
  unknown_key: -1
  date_spine_start: '2025-01-01'
  date_spine_end: '2028-01-01'